config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root to: "pages#home"

    devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    resources :users do
      get 'index' => 'users#index'
    end

    resources :companies do
      get 'qr' => 'companies#qr'
      resources :stations, only: %i[show create edit destroy]
    end

    post '/companies/new' => 'companies#new'
    resources :menus
    post '/menus/cmUpdate' => 'menus#cmUpdate'
    post '/users/update' => 'users#update'
    post '/items/setPrices' => 'items#setPrices'

    resources :items do
      resources :subitems, only: %i[new create update destroy]
    end

    post '/bsktresqto', to: 'deliveries#grequest'
  end
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :company
  has_many :orders
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_stations, only: %i[show destroy edit update]

  def index
    @stations = policy_scope(Station)
  end

  def show
    authorize @station

    @station = Station.find(params[:id])
    @orders = Order.where(station_id: @station.id)

    orders_id = @orders.map(&:id)
    @order_items = OrderItem.where(order_id: orders_id)

    items_id = @order_items.map(&:item_id)
    @items = Item.where(id: items_id)

    subitems_id = @order_items.map(&:subitem_id)
    @subitems = Subitem.where(id: subitems_id)
  end

  def create
    @station = Station.new(station_params)
    authorize @station
    @station.save!
    redirect_to station_path(@station.company_id)
  end

  def edit
    authorize @station
  end

  def update
    authorize @station
    @station.update(station_params)
    redirect_to station_path(@station.company_id)
  end

  def destroy
    authorize @station
    @station.destroy!
    redirect_to company_path(current_user)
  end

  private

  def station_params
    params.require(:station).permit(:name, :company_id)
  end

  def set_stations
    @station = Station.find(params[:id])
  end
end

app/views/stations/_order.html.erb
<div  class="stn-show-order-list col-sm-6 col-md-4 col-xl-2" id="<%= dom_id(order) %>" >
  <div class="stn-show-order-list-top">
    <h5>Table #: <%= order.table %></h5>
    <p><%= order.created_at %></p>
  </div>
  <hr>
  <div class="stn-show-order-list-content">
    <ol>
      <% order_items.each do |order_item|  %>
        <% if order_item.order_id == order.id %>
          <% items.each do |item| %>
            <% if item.id == order_item.item_id %>
              <li><%= item.name %></li>
              <% if order_item.subitem_id %>
                <% subitems.each do |subitem| %>
                  <% if subitem.id == order_item.subitem_id %>
                    <p><%= subitem.name %></p>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </ol>
  </div>
  <div class="stn-show-order-list-total">
    <hr>
    <p>Total : <%= order.total %></p>
  </div>
</div>

app/views/stations/_orders.html.erb
<div class="row" id="orders">
  <% orders.each do |order| %>
    <%= render partial: "stations/order", locals: { order: order, order_items: order_items, items: items, subitems: subitems } %>
  <% end %>
</div>

app/views/stations/index.html.erb
<%= render partial: "shared/navbar", locals: {btnN: "NEW STATION", btnE: "EDIT STATION", btnL: "LOG OUT" }  %>
<h1>INDEX</h1>
<% @stations.each do |station| %>
  <div><%= station.name %></div>
<% end %>

app/views/stations/show.html.erb
<%= render partial: "shared/navbar-area", locals: {button_a: t('landing_page.home'), button_b: t('landing_page.product'), button_c: t('landing_page.pricing'), button_d: t('landing_page.contact') } %>
<div class="stn-sw-container">
  <div class="stn-sw-ctn-title">
    <h2><%= @station.name %></h2>
  </div>
  <%= turbo_stream_from "station_#{@station.id}" %>
  <div class="stn-sw-orders" >
    <%= render partial: 'stations/orders', locals: { orders: @orders, order_items: @order_items, items: @items, subitems: @subitems } %>
  </div>
  <div>
    <%= link_to "Back to index", companies_path %>
  </div>
</div>