config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root to: "pages#home"

    devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    resources :users do
      get 'index' => 'users#index'
    end

    resources :companies do
      get 'qr' => 'companies#qr'
      resources :stations, only: %i[show create edit destroy]
    end

    post '/companies/new' => 'companies#new'
    resources :menus
    post '/menus/cmUpdate' => 'menus#cmUpdate'
    post '/users/update' => 'users#update'
    post '/items/setPrices' => 'items#setPrices'

    resources :items do
      resources :subitems, only: %i[new create update destroy]
    end

    post '/bsktresqto', to: 'deliveries#grequest'
  end
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :menus
  has_many :items, through: :menus
  has_many :subitems, through: :items
  has_many :stations, dependent: :delete_all
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_companies, only: %i[show edit update destroy indexMenuList]
  def index
    @company = policy_scope(Company)
    @company.sort_by(&:id)
    set_master_role
    set_qr
    @menus = current_user.menus
    @menus.sort_by(&:position)
    @stations = current_user.stations
  end

  def show
    authorize @company
    @companies = Company.where(user_id: current_user)
    @main_station_id = Station.where(company_id: @company.id, name: "Main station").pluck(:id).first
    set_menus
    set_items
    set_subitems
  end

  def new
    @company = Company.new
    @companies = Company.where(user_id: current_user)
    authorize @company
  end

  def create
    @company = Company.new(company_params)
    authorize @company
    @company.user = current_user
    if @company.save
      main_station
      redirect_to companies_path
    else
      render :new
    end
  end

  def edit
    authorize @company
    @menus = Menu.where(company_id: @company)
  end

  def update
    authorize @company
    @company.update(company_params)
    redirect_to companies_path
  end

  def destroy
    authorize @company
    @company.destroy
    redirect_to companies_path
  end

  def qr
    @company = Company.find(params[:company_id])
    authorize @company
    @qr_code = RQRCode::QRCode.new(@company.qr_code)
    @svg = @qr_code.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 5,
      standalone: true
    )
  end

  private

  def company_params
    params.require(:company).permit(:name, :city, :suburb, :street, :number, :post, :qr_code)
  end

  def set_companies
    @company = Company.find(params[:id])
  end

  def set_menus
    @menus = Menu.where(company_id: @company.id)
    @menus = @menus.sort_by(&:position)
    @menu = Menu.new
  end

  def set_items
    @items = @company.items
    @items = @items.sort_by(&:position)
    @item = Item.new
  end

  def set_subitems
    @subitems = @company.subitems
    @subitem = Subitem.new
  end

  def set_qr
    @company.each do |company|
      next unless company.qr_code

      @qr_code = RQRCode::QRCode.new(company.qr_code)
      @svg = @qr_code.as_svg(offset: 0, color: '000', shape_rendering: 'crispEdges', module_size: 1, standalone: true)
    end
  end

  def set_master_role
    if current_user.role.name == "master"
      @users = User.all
      @users = User.order(id: :desc)
      @companies = Company.where(user_id: current_user.id)
    elsif current_user.present?
      @companies = Company.where(user_id: current_user.id)
    end
  end

  def main_station
    station = Station.new
    station.name = "Main station"
    station.company_id = @company.id
    station.save!
  end
end

app/views/companies/show-settings/_edit-subitem.html.erb
<div class="sh-subitem-form-toggle-<%= subitem.id %> sh-form-inputs" style="display: none;">
  <%= simple_form_for subitem, url:item_subitem_path(item), method: :patch do |f| %>
    <div class="sh-inputs-name-price">
      <div class="sh-input-name">
        <%= f.text_field :name, class: "sh-subitem-input-name-#{subitem.id}", placeholder: "#{subitem.name}", label: false %>
        <%= f.hidden_field :subitem_id, value: subitem.id %>
        <button  onclick="nameInput(<%= subitem.id %>); return false" return false>X</button>
      </div>
      <div class="sh-input-price">
        <%= f.text_field :price, type:"number", step:"0.01", class: "sh-subitem-input-price-#{subitem.id}", placeholder: "#{subitem.price}", label: false%>
      </div>
    </div>
    <div class="sh-input-description">
      <%= f.text_area :description, class: "sh-subitem-input-description-#{subitem.id}", placeholder: "#{subitem.description}", label: false, rows: 2 %>
      <button  onclick="descriptionInput(<%= subitem.id %>); return false">X</button>
    </div>
    <div class="sh-input-btns">
      <%= f.submit "UPDATE",class:"sh-btn-set-item" %>
      <%= f.submit "RESET", type:"reset", class:"sh-btn-set-item" %>
    </div>
  <% end %>
</div>

app/views/companies/show-settings/_item-set.html.erb
<div class="sh-form-toggle-<%= item.id %> sh-form-inputs" style="display: none;">
  <%= simple_form_for(item) do |f| %>
    <div class="sh-inputs-name-price">
      <div class="sh-input-position">
        <%= f.text_field :position, type:"number", step:"1.0", value:"#{ item.position }", label: false %>
      </div>
      <div class="sh-input-name">
        <%= f.text_field :name, class: "sh-input-name-#{item.id}", placeholder: "#{item.name}", label: false %>
        <button  onclick="nameInput(<%= item.id %>); return false" return false>X</button>
      </div>
      <div class="sh-input-price">
        <%= f.text_field :price, type:"number", step:"0.01", class: "sh-input-price-#{item.id}", placeholder: "#{item.price}", label: false%>
      </div>
    </div>
    <div class="sh-input-description">
      <%= f.text_area :description, class: "sh-input-description-#{item.id}", placeholder: "#{item.description}", label: false, rows: 2 %>
      <button  onclick="descriptionInput(<%= item.id %>); return false">X</button>
    </div>
    <div class="sh-input-btns">
      <%= f.submit "UPDATE",class:"sh-btn-set-item" %>
      <%= f.submit "RESET", type:"reset", class:"sh-btn-set-item" %>
      <button  class="sh-btn-set-item btn-subitem" data-id=<%= item.id %> onclick="addSubitem(this); return false" return false>ADD SUBITEM</button>
      <button  onclick="editItem(this)" data-id=<%= item.id %> class="sh-btn-set-item" type="reset">CANCEL</button>
    </div>
  <% end %>
  <% @subitems.each do |subitem| %>
    <% if subitem.item_id == item.id %>
      <div class="sh-items-name-price option sh-subitem-toggle-<%= subitem.id %>">
        <div class="sh-items-input-option">
          <div class="sh-items-option">
            <h5><%= subitem.name %></h5>
          </div>
        </div>
        <div class="sh-items-option-price">
          <button class="sh-btn-set-item sh-subitem-btn-edit-<%= subitem.id %>" onclick="editSubitem(this)" data-id=<%= subitem.id %>>EDIT</button>
        </div>
      </div>
      <%= render partial: "companies/show-settings/edit-subitem", locals: {item: item, subitem: subitem} %>
    <% end %>
  <% end %>
  <%= render partial: "companies/show-settings/new-subitems", locals: {item: item, subitem: @subitem} %>
</div>

app/views/companies/show-settings/_new-item.html.erb
<% if current_user.present? %>
  <% if (current_user == @company.user) || (current_user.role_id == 1) %>
    <div class="sh-new-form-toggle-<%= menu.id %> sh-form-inputs" style="display: none;">
      <div class="sh-form-title">
        <p>Create new item:</p>
      </div>
      <%= simple_form_for @item, url:items_path, method: :post do |f| %>
        <div class="sh-inputs-name-price">
          <div class="sh-input-name">
              <%= f.text_field :name, class: "sh-new-input-name", placeholder: "name", label: false %>
          </div>
          <div class="sh-input-price">
            <%= f.text_field :price, type:"number", step:"0.01", class: "sh-new-input-price", value: '%.2f' % 0.00, label: false%>
          </div>
        </div>
        <div class="sh-input-description sh-new-input-description">
          <%= f.text_area :description, placeholder: "description", label: false, rows: 2 %>
        </div>
        <%= f.input :menu_id, :as => :hidden, input_html: { value:menu.id}, label: false%>
        <div class="sh-input-btns">
          <%= f.submit "CREATE", class:"sh-btn-set-item" %>
          <button  onclick="addItem(this)" data-id=<%= menu.id %> class="sh-btn-set-item" type="reset">CANCEL</button>
        </div>
      <% end %>
    </div>
    <div class="sh-div-btn-add">
      <button class="sh-btn-add" onclick="addItem(this)" data-id=<%= menu.id %>> ADD NEW ITEM </button>
    </div>
  <% end %>
<% end %>

app/views/companies/show-settings/_new-section.html.erb
<% if current_user.present? %>
  <% if (current_user == @company.user) || (current_user.role_id == 1) %>
    <div class="sh-form-add-new-section">
      <%= simple_form_for @menu, url:menus_path, method: :post do |f| %>
        <div class="sh-form-inputs-new-section">
          <%= f.button :submit, "ADD NEW SECTION", class:"btn-nw-section" %>
          <%= f.input :title, :as => :hidden, value:"Menu" %>
          <%= f.text_field :subtitle, placeholder:"Title" %>

            <%= f.text_field :position, class: "position-input" %>
            <label for="position">Position</label>
          
          <%= f.input :company_id, :as => :hidden, input_html: { value:@company.id}  %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/companies/show-settings/_new-subitems.html.erb
<div class="sh-form-new-subitem-toggle-<%= item.id %> sh-form-inputs" style="display: none;">
  <div class="sh-form-new-subitem-label">
    <p>new subitem for : <%= item.name %></p>
  </div>
  <%= simple_form_for @subitem, url:item_subitems_path(item), method: :post do |f| %>
    <div class="sh-inputs-name-price">
      <div class="sh-input-name">
          <%= f.text_field :name, class: "sh-new-input-name", placeholder: "name", label: false %>
      </div>
      <div class="sh-input-price">
        <%= f.text_field :price, type:"number", step:"0.01", class: "sh-new-input-price", value: '%.2f' % 0.00, label: false%>
      </div>
    </div>
    <div class="sh-input-description sh-new-input-description">
      <%= f.text_area :description, placeholder: "description", label: false, rows: 2 %>
    </div>
    <div class="sh-input-checkbox">
      <%= f.input :sumitem, label: "sum price"%>
      <div class="sh-input-checkbox-form-btns">
        <%= f.submit "CONFIRM",class:"sh-btn-set-item" %>
        <%= f.submit "RESET", type:"reset", class:"sh-btn-set-item" %>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/show-settings/_prices-set.html.erb
<% if current_user.present? %>
<% if (current_user == @company.user) || (current_user.role_id == 1) %>
    <form action="<%= items_setPrices_path %>" method="POST">
    <div class="sh-div-set-prices">
        <div class="sh-inputs-set-prices">
        <div>
            <p>Change all prices for:</p> 
        </div>
        <div class="sh-input-euro">
            <input type="number" name="euro"  value= "0.00" step="0.01" /><p><strong>€</strong></p> 
        </div>
        <div class="sh-input-percent">
            <input type="number" name="percent" value= "0" step="0.1" /><p><strong>%</strong></p>
        </div>
        </div>
        <div>
        <input type="hidden" name="menu" value= "<%= menu.id %>" />
        <input type="submit" value="SEND" class="sh-btn-set-item" />
        </div>
    </div>
    </form>
<% end %>
<% end %>

app/views/companies/show-settings/_section-set.html.erb
<div class="sh-card-title-btns">
    <p class="sh-card-title-toggle-<%= menu.id%> sh-p-search-title"><strong><%= menu.subtitle.upcase %></strong></p>
    <div class="sh-input-menu-title-toggle-<%= menu.id%>" style="display: none;">
    <%= simple_form_for(menu) do |f| %>
        <div class="sh-card-form-menu">
        <div class="sh-card-form-subtitle">
            <p>Title</p>
            <%= f.text_field :subtitle, value:"#{menu.subtitle}" %>
        </div>
        <div class="sh-card-form-position">
            <p>Position</p>
            <%= f.number_field :position, value:"#{ '%.1f' %  menu.position }" %>
        </div>
        <div class="sh-card-form-visible">
            <p>Visible</p>
            <%= f.check_box :visible, value:"#{ menu.visible }" %>
        </div>
        <div class="sh-card-form-btn-update">
            <%= f.submit "UPDATE",class:"sh-btn-set-item sh-btn-edit-section sh-form-title-menu" %>
            <button class="sh-btn-set-item sh-btn-edit-section" type="reset" onclick="editMenu(this)" data-id=<%= menu.id %>>CANCEL</button> 
        </div>
        </div>
    <% end %>
    <hr>
    </div>
    <div class="sh-card-edit-delete sh-card-edit-delete-toggle-<%= menu.id%>">
    <% if current_user.present? %>
      <% if (current_user == @company.user) || (current_user.role_id == 1)  %>
        <div>
          <button class="sh-btn-set-item sh-btn-edit-section" onclick="editMenu(this)" data-id=<%= menu.id %>>EDIT</button>                
        </div>
        <div>
          <%= button_to "DELETE SECTION", menu_path(menu), class:"sh-btn-set-item sh-btn-delete-section", method: :delete %>
        </div>
      <% end %>
    <% end %>
    </div>
</div>