config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root to: "pages#home"

    devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    resources :users do
      get 'index' => 'users#index'
    end

    resources :companies do
      get 'qr' => 'companies#qr'
      resources :stations, only: %i[show create edit destroy]
    end

    post '/companies/new' => 'companies#new'
    resources :menus
    post '/menus/cmUpdate' => 'menus#cmUpdate'
    post '/users/update' => 'users#update'
    post '/items/setPrices' => 'items#setPrices'

    resources :items do
      resources :subitems, only: %i[new create update destroy]
    end

    post '/bsktresqto', to: 'deliveries#grequest'
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_homelogin.html.erb
<h1>Index company</h1>

<% @company.reverse_each do |company| %>
  <ul class = "home-company-list">
  <li><%= company.name %></li>
  </ul>
<% end %>

app/views/shared/_navbar-area.html.erb
<section class="navbar-area navbar-nine sticky">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <nav class="navbar navbar-expand-lg">
          <a class="navbar-brand" href="#">
            <%= image_tag('icons/white-logo.svg', alt: 'Logo') %>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNine"
            aria-controls="navbarNine" aria-expanded="false" aria-label="Toggle navigation">
            <span class="toggler-icon"></span>
            <span class="toggler-icon"></span>
            <span class="toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse sub-menu-bar" id="navbarNine">
            <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="page-scroll active" href="#hero-area"><%= button_a %></a>
            </li>
            <li class="nav-item">
              <a class="page-scroll" href="#product"><%= button_b %></a>
            </li>

            <li class="nav-item">
              <a class="page-scroll" href="#pricing"><%= button_c %></a>
            </li>
            <li class="nav-item">
              <a class="page-scroll" href="#contact"><%= button_d %></a>
            </li>
            </ul>
          </div>
          <div class="navbar-language-selector">
            <%= link_to "EN", url_for(locale: :en) %> |
            <%= link_to "DE", url_for(locale: :de) %>
          </div>
          <div class="navbar-btn d-none d-lg-inline-block">
            <% unless user_signed_in? %>
              <%= link_to t('landing_page.login'), new_user_session_path, class: "btn btn-primary" %>
              <%= link_to t('landing_page.sign_up'), new_user_registration_path, class: "btn btn-primary" %>
            <% else %>
              <%= link_to t('landing_page.logout'), destroy_user_session_path, class: "btn btn-primary" %>
            <% end %>

          </div>
        </nav>
      </div>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<div class="cmp-index-navbar">
  <div class="cmp-index-navbar-cont">
    <div  class="cmp-index-navbar-btn">
      <%= button_to button_new_company,  new_company_path, method: :get, class:"cmp-index-btn-lgt  h-btn" %>
    </div>
    <div class="cmp-index-navbar-btn">
      <%= button_to button_edit,  edit_user_registration_path, method: :get, class:"cmp-index-btn-lgt  h-btn" %>
    </div>
    <div class="cmp-index-navbar-btn">
      <%= button_to button_logout,  destroy_user_session_path, method: :get, class:"cmp-index-btn-lgt  h-btn" %>
    </div>
  </div>
</div>