config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root to: "pages#home"

    devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    resources :users do
      get 'index' => 'users#index'
    end

    resources :companies do
      get 'qr' => 'companies#qr'
      resources :stations, only: %i[show create edit destroy]
    end

    post '/companies/new' => 'companies#new'
    resources :menus
    post '/menus/cmUpdate' => 'menus#cmUpdate'
    post '/users/update' => 'users#update'
    post '/items/setPrices' => 'items#setPrices'

    resources :items do
      resources :subitems, only: %i[new create update destroy]
    end

    post '/bsktresqto', to: 'deliveries#grequest'
  end
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :menus
  has_many :items, through: :menus
  has_many :subitems, through: :items
  has_many :stations, dependent: :delete_all
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_companies, only: %i[show edit update destroy indexMenuList]
  def index
    @company = policy_scope(Company)
    @company.sort_by(&:id)
    set_master_role
    set_qr
    @menus = current_user.menus
    @menus.sort_by(&:position)
    @stations = current_user.stations
  end

  def show
    authorize @company
    @companies = Company.where(user_id: current_user)
    @main_station_id = Station.where(company_id: @company.id, name: "Main station").pluck(:id).first
    set_menus
    set_items
    set_subitems
  end

  def new
    @company = Company.new
    @companies = Company.where(user_id: current_user)
    authorize @company
  end

  def create
    @company = Company.new(company_params)
    authorize @company
    @company.user = current_user
    if @company.save
      main_station
      redirect_to companies_path
    else
      render :new
    end
  end

  def edit
    authorize @company
    @menus = Menu.where(company_id: @company)
  end

  def update
    authorize @company
    @company.update(company_params)
    redirect_to companies_path
  end

  def destroy
    authorize @company
    @company.destroy
    redirect_to companies_path
  end

  def qr
    @company = Company.find(params[:company_id])
    authorize @company
    @qr_code = RQRCode::QRCode.new(@company.qr_code)
    @svg = @qr_code.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 5,
      standalone: true
    )
  end

  private

  def company_params
    params.require(:company).permit(:name, :city, :suburb, :street, :number, :post, :qr_code)
  end

  def set_companies
    @company = Company.find(params[:id])
  end

  def set_menus
    @menus = Menu.where(company_id: @company.id)
    @menus = @menus.sort_by(&:position)
    @menu = Menu.new
  end

  def set_items
    @items = @company.items
    @items = @items.sort_by(&:position)
    @item = Item.new
  end

  def set_subitems
    @subitems = @company.subitems
    @subitem = Subitem.new
  end

  def set_qr
    @company.each do |company|
      next unless company.qr_code

      @qr_code = RQRCode::QRCode.new(company.qr_code)
      @svg = @qr_code.as_svg(offset: 0, color: '000', shape_rendering: 'crispEdges', module_size: 1, standalone: true)
    end
  end

  def set_master_role
    if current_user.role.name == "master"
      @users = User.all
      @users = User.order(id: :desc)
      @companies = Company.where(user_id: current_user.id)
    elsif current_user.present?
      @companies = Company.where(user_id: current_user.id)
    end
  end

  def main_station
    station = Station.new
    station.name = "Main station"
    station.company_id = @company.id
    station.save!
  end
end

app/views/companies/_form.html.erb
<%= simple_form_for(company) do |f| %>
  <div class="form-inputs cmp-new-form-inputs">
    <%= f.input :name, class:"form-item"%>
    <%= f.input :city, class:"form-item" %>
    <%= f.input :suburb, class:"form-item" %>
    <%= f.input :street, class:"form-item" %>
    <%= f.input :number, class:"form-item" %>
    <%= f.input :post, class:"form-item" %>
  </div>
    
  <div class="form-actions">
    <%= f.submit class:"New" %>
  </div>
<% end %>

app/views/companies/_index-users-list.html.erb
<div class="cmp-index-users-list-container">
  <% if current_user.role.name == "master"  %>
    <div>
      <p>Users:</p>
      <hr>
      <div class="cmp-index-users-list">
        <% @users.each do |user| %>
          <% if user != current_user %>
            <%= simple_form_for user, :url => users_update_path(user), :method => :post do |f| %>
              <div class="cmp-index-users-list-user-box">
                <p><strong><%= user.email %></strong></p>
                <div class="cmp-index-users-list-user-inputs">
                  <div class="cmp-index-users-list-user-inputs-sc">
                    <div class="cmp-index-users-list-user-inputs-sc-select">
                      <%= f.select :role, ["#{user.role.name}","master", "manager"] %>
                    </div>
                    <div class="cmp-index-users-list-user-inputs-sc-checkbox">
                      <%= f.hidden_field :user_id, value:user.id %>
                      <%= f.check_box :active, id:"active", value:user.active %>
                      <label for="active"><p>Active</p></label>
                    </div>
                    <div class="cmp-index-users-list-user-submit">
                      <%= f.submit "CONFIRM", class:"sh-btn-set-item" %>
                    </div>
                  </div>
                </div>
                <div class="cmp-index-users-list-user-inputs-companies">
                  <% @company.each do |company| %>
                    <% if company.user == user %>
                      <div class="cmp-index-users-list-user-inputs-companies-name">
                        <li><%= company.name %></li>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %><br>
      </div>
    </div>
  <% end %>
  <hr>
</div>

app/views/companies/edit.html.erb
<div class="cmp-new-container">
  <div class="cmp-new-content">
    <h2>Edit company</h2>
    <%= simple_form_for(@company) do |f| %>
      <div class="form-inputs cmp-new-form-inputs">
        <%= f.input :name, class:"form-item"%>
        <%= f.input :city, class:"form-item" %>
        <%= f.input :suburb, class:"form-item" %>
        <%= f.input :street, class:"form-item" %>
        <%= f.input :number, class:"form-item" %>
        <%= f.input :post, class:"form-item" %>
      </div>
      <div class="form-actions">
        <%= f.submit class:"New" %>
      </div>
    <% end %>
    <br>
    <h3>Menus</h3>
    <div>
      <% @menus.each do |menu| %>
        <div class="cmp-edit-menu">
          <h5><%= menu.subtitle %></h5>
          <div class="cmp-edit-menu-checkbox">
            <label for="menu-<%= menu.id %>" class="cmp-edit-menu-checkbox-label">Visible</label>
            <a href=""></a><input type="checkbox" id="menu-<%= menu.id %>" <%= menu.visible ? 'checked' : '' %>>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="cmp-index-container clearfix">
  <%= render partial: "shared/navbar-area", locals: { button_a: t('landing_page.home'), button_b: t('landing_page.product'), button_c: t('landing_page.pricing'), button_d: t('landing_page.contact') } %>
  <div class="cmp-index-container-cont">
    <div class="cmp-index-content">
      <div class="cmp-index-cont-sides leftcontainer">
          <%= render partial: "companies/render-companies-index/windows-dinamic", locals: {companies: @companies, stations: @stations} %>
      </div>
    </div>
  </div>
  <% if current_user.role == "master" %>
    <%= render partial: "index-users-list" %>
  <% end %>
</div>

<%= javascript_include_tag "packs/idx-cmp-show" %>

app/views/companies/index_change.html.erb
  <div class="cmp-index-cards row">
    <% @company = @company.sort_by(&:id) %>
    <% @company.each do |company| %>
      <% if current_user == company.user  %>
        <div class="cmp-index-card-btns col-sm-6 col-md-4 col-xl-1 list">
          <div class="cmp-index-card">
            <a href="<%= company_path(company) %>"class="cmp-index-card-content">
              <div class="cmp-index-card-tittle">
                <h4><strong><%= company.name.upcase %></strong></h4>
              </div>
              <div class="cmp-index-card-address">
                <p><%= company.street %> <%= company.number %>, <%= company.post %> <%= company.city %></p>
              </div>
            </a>
          </div>
          <div class="cmp-index-card-qr">
            <% if company.qr_code == nil %>
              <%= simple_form_for(company) do |f| %>
                <%= f.hidden_field :qr_code, value:"https://fillo.herokuapp.com#{company_path(company)}"%>
                <div class="cmp-index-card-qr-g">
                  <%= f.submit "Generate QR", class:"sh-btn-set-item"%>
                </div>
              <% end %>
            <% else %>
              <div class="cmp-index-card-svg">
                <%= link_to company_qr_path(company_id: company.id) do %>
                  <%= @svg.html_safe %>
                <% end %>
              </div>
            <% end %>
          </div>

          <div class="cmp-index-card-set-btns">
            <%= button_to "EDIT", edit_company_path(company), method: :get %>
            <%= button_to "DELETE", company_path(company), method: :delete %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

        <div class="cmp-index-cont-sides">
        <%= render partial: "companies/render-companies-index/companies-index-cont-right",  locals: {company: @company} %>
      </div>
    <div class="cmp-index-card-sections-checkbx-checkboxes-row">
      <% @menus = @menus.sort_by(&:position) %>
      <% @menus.each do |menu| %>
        <%= simple_form_for menu, :url => menus_cmUpdate_path(menu), :method => :post do |f| %>
          <div class="cmp-index-card-sections-checkbx-checkboxes">
            <div class="cmp-index-card-sections-checkbx-checkboxes-box-name">
              <%= f.hidden_field :menu_id, value:menu.id %>
              <%= f.check_box :visible, value:menu.visible %>
              <label for="<%= menu.subtitle %>"><p><%= menu.subtitle %></p></label>
            </div>
            <div class="cmp-index-card-sections-checkbx-checkboxes-submit">
              <%= f.submit "CONFIRM", class:"sh-btn-set-item" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

  <div class="cmp-index-card-sections-checkbx-checkboxes-row">
      <% @menus = @menus.sort_by(&:position) %>
      <% @menus.each do |menu| %>
        <div class="cmp-index-card-sections-checkbx-checkboxes">
          <%= simple_form_for menu, :url => menus_cmUpdate_path(menu), :method => :post do |f| %>
            <div class="cmp-index-card-sections-checkbx-checkboxes-box-name">
              <%= f.hidden_field :menu_id, value:menu.id %>
              <%= f.check_box :visible, value:menu.visible %>
              <label for="<%= menu.subtitle %>"><p><%= menu.subtitle %></p></label>
            </div>
            <div class="cmp-index-card-sections-checkbx-checkboxes-submit">
              <%= f.submit "UPDATE", class:"sh-btn-set-item" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

app/views/companies/new.html.erb
<div class="cmp-new-container">
  <div class="cmp-new-content">
    <h1>New company</h1>
    <%= render "form", company: @company %>
  </div>
</div>

app/views/companies/qr.html.erb
<div class="qr-container">
  <div class="qr-svg">
    <%= @svg.html_safe %>
  </div>
</div>

app/views/companies/show.html.erb
<%= render partial: "companies/show-basket/basket-paper", locals: {company: @company} %>
<div class = "sh-container">
  <div class="sh-nav">
    <h1><%= t("menu") %></h1>
  </div>
  <% if @company.basket %>
    <a href="#" onclick="toggle(); return false">
      <div class="sh-nav-basket">
      </div>
    </a>
  <% end %>
  <div class="sh-searchform">
    <input type="text" name="search" autocomplete=”off” id="sh-input"
    onkeyup="searchbar()" placeholder="Search">
  </div>
  <%= render partial: "companies/show-settings/new-section" %>
  <div class="sh-cards row" id="wrapper">
    <hr>
    <% @menus.each do |menu|  %>
      <% if menu.visible == true %>
        <div class="sh-card col-sm-6 col-md-4 col-xl-2 list">
          <div class="sh-card-content">
            <%= render partial: "companies/show-settings/section-set", locals: {menu: menu} %>
            <div class="sh-items">
              <% @items.each do |item|  %>
                <% if item.menu_id == menu.id %>
                  <div class='sh-items-li'>
                    <%= render partial: "companies/show-settings/item-set", locals: {item: item, subitems: @subitems, subitem: @subitem} %>
                    <div class="sh-p-search">
                      <div class="sh-item-toggle-<%= item.id %>">
                        <div class="sh-items-name-price">
                          <h5 class="sh-item-<%= item.id %>"><strong><a href="#" data-id="<%= item.id %>" data-name="<%= item.name %>" data-price="<%= item.price %>" onclick="basketItems(event, this)"><%= item.name.upcase %></h5></a><h5 class="sh-item-<%= item.id %>">€<%= '%.2f' % item.price %></strong></h5>
                        </div>
                        <div class="sh-items-description">
                          <p class="sh-item-<%= item.id %>"><%= item.description.gsub(/\n/, '<br>').html_safe %></p>
                        </div>
                        <%# SUBITEM %>
                        <% @subitems.each do |subitem| %>
                          <% if subitem.item_id == item.id %>
                            <div class="sh-items-name-price option">
                              <div class="sh-items-input-option">
                                <div class="sh-items-input">
                                  <%= check_box_tag 'check_box', 1, false, id: "a", class:"options-checkboxes-#{subitem.id} checkboxes-subitems-#{item.id}" %>
                                </div>
                                <div class="sh-items-option">
                                  <h5 class="sh-item-<%= item.id %>"><strong><%= subitem.name %></h5></strong>
                                  <p class="sh-item-<%= item.id %>"><%= subitem.description.gsub(/\n/, '<br>').html_safe %></p>
                                </div>
                              </div>
                              <div class="sh-items-option-price">
                                <h5 class="sh-item-<%= item.id %> options-prices-<%= item.id %>">€<%= '%.2f' % subitem.price %></h5>
                              </div>
                            </div>
                          <% end %>
                        <% end %>
                        <%# SUBITEM %>
                      </div>
                      <div class="sh-div-btn-set-item">
                        <% if @company.basket %>
                          <div class="sh-div-item-basket-img">
                          </div>
                          <div class="sh-div-item-basket-quantity" id="quantityDiv<%= item.id %>">
                            <p><span id="sh-div-item-basket-quantity-number-<%= item.id %>"></span></p>
                          </div>
                          <button class="sh-btn-basket-item" data-id="<%= item.id %>" data-item="<%= item.to_json %>" data-subitems="<%= @subitems.to_json %>" onclick="basketItems(event, this, true)" >+</button>
                          <button class="sh-btn-basket-item" data-id="<%= item.id %>" data-item="<%= item.to_json %>" data-subitems="<%= @subitems.to_json %>" onclick="basketItems(event, this, false)" >-</button>
                        <% end %>
                        <% if current_user.present? %>
                          <% if (current_user == @company.user) || (current_user.role_id == 1) %>
                            <button class="sh-btn-set-item sh-btn-edit-<%= item.id %>" onclick="editItem(this)" data-id=<%= item.id %>>EDIT</button>
                            <%= button_to "DELETE", item_path(item), class:"sh-btn-set-item sh-btn-delete-#{item.id}", method: :delete %>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <%= render partial: "companies/show-settings/prices-set", locals: {menu: menu} %>
            </div>
            <%= render partial: "companies/show-settings/new-item", locals: {menu: menu} %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= render partial: "companies/show-settings/new-section" %>
</div>

<%= javascript_include_tag "packs/sh-searchbar" %>
<%= javascript_include_tag "packs/sh-edit-item" %>
<%= javascript_include_tag "packs/sh-add-item" %>
<%= javascript_include_tag "packs/sh-edit-menu" %>
<%= javascript_include_tag "packs/sh-basket" %>
<%= javascript_include_tag "packs/sh-basket-open" %>
<%= javascript_include_tag "packs/sh-new-subitem" %>
<%= javascript_include_tag "packs/sh-edit-subitem" %>